default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: playTogether_development

test:
  <<: *default
  database: playTogether_test

production:
  <<: *default
  database: playTogether_production
  username: playTogether
  password: <%= ENV['PLAYTOGETHER_DATABASE_PASSWORD'] %>
